### ISSUE TITLE
Pull and Push

### ISSUE THREAD

**Issue by NurRobin** [jenskuespert/KGSSB#3]
![Desktop Screenshot 2019 06 29 - 09 00 04 20](https://user-images.githubusercontent.com/52316721/60380843-4954d880-9a4c-11e9-85b2-7c71536af98b.png)

**Comment by jenskuespert** [comment]
Hallo Robin,

du solltest eine Einladung von mir im Postkasten haben. Falls nicht, kannst Du den Zugang zum Projekt auch hier 

https://github.com/jenskuespert/KGSSB/invitations

aktivieren.

    - J.Küspert -

**Comment by jenskuespert** [comment]
mit Robin gesprochen, sollte nun gehen
